# Generated by Django 5.0.4 on 2024-04-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='detail_img/'),
        ),
    ]
