# Generated by Django 5.0.4 on 2024-04-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_detail_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='detail_img/', verbose_name='Изображение'),
        ),
    ]
