# Generated by Django 5.0.4 on 2024-04-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_detail_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='detail_description',
            field=models.TextField(default='', max_length=500, verbose_name='Описание'),
        ),
    ]
